profiles:
  - profileName: profile1
    description: "description profile1xxxxxx"
    projectId: Aaa
    vCenterAccount: "vCenterPraha"
    terminateConditions:
      terminateAfterBuild: true
    imageConfigJson:
      "image-name":
        template: datacenter/vm/tc-agent-template
        instanceFolder: datacenter/vm/tc-agents
        agentPool: "asdasdasd"
        resourcePool: aaaa
        maxInstances: 1
        network: "sasda"
      "image-name2":
        template: datacenter/vm/tc-agent-template
        instanceFolder: datacenter/vm/tc-agents
        maxInstances: 10
        network: []
  - profileName: profile2
    description: "profile desc 2"
    projectId: Aaa
    vCenterAccount: "vCenterPraha"
    enabled: false
    terminateConditions:
      terminateAfterBuild: true
    imageConfigJson:
      "image-name3":
        template: datacenter/vm/tc-agent-template
        instanceFolder: datacenter/vm/tc-agents
        resourcePool: aaaa
        agentPool: 10
        maxInstances: 10

  - profileName: profile4
    description: "profile desc 4"
    projectId: Aaa
    vCenterAccount: "vCenterPraha"
    terminateConditions:
      terminateAfterBuild: true
    imageConfigJson:
      "image-name211":
        template: datacenter/vm/tc-agent-template
        instanceFolder: datacenter/vm/tc-agents
        resourcePool: aaaa
        agentPool: "asdasd"
        maxInstances: 10
        "network": "datacenter/network/agent-network"
